name = "kto-checkout"
main = "worker.js"
compatibility_date = "2024-11-01"

# Filled in automatically after we create the KV namespace.
[[kv_namespaces]]
binding = "KV"
id = "PLACEHOLDER"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "kto-images"
